services:
  - type: web
    name: guru-server
    env: python
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PORT
        value: 8000
    autoDeploy: false
    plan: free
