services:
  - type: web
    name: guru-server
    env: python
    region: singapore
    buildCommand: chmod +x render.build.sh && ./render.build.sh
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PYTHONUNBUFFERED
        value: "true"
    autoDeploy: false
